### ISSUE TITLE
Support for OpenBSD/adJ in order to port mytonctrl to that OS

### ISSUE THREAD

**Issue by vtamara** [igroman787/mypylib#7]
In its current state mypylib as used by mytonctrl doesn't work on OpenBSD/adJ because:

1. It uses a fixed path for python3 `/usr/bin/python3`, but in OpenBSD/adJ it is at `/usr/local/bin/python3`
2. The function `GetLoadAvg` supports Linux and FreeBSD/Darwin but not OpenBSD/adJ because the format of `sysctl -n vm.loadavg` is different
3. The function `GetInternetInterfaceName` uses the command `ip` that doens't exist on OpenBSD/adJ, but what is needed can be done with the command `ifconfig`
4. The function `RunAsRoot` has support for Ubuntu running with `sudo` but not for OpenBSD/adJ where the standard is to use `doas`
5. The functions  `Add2Systemd` and `GetServiceStatus` are specific for OS with `systemd`, however they can be improved to support the initialization system of OpenBSD with `rcctl` instead of `systemctl` and for adJ with the right format for services in files in `/etc/rc.d`

**Comment by igroman787** [comment]
Merged: https://github.com/igroman787/mypylib/pull/6
